### ISSUE TITLE
Փոխելու բան կա սնեչում, աչքի տակ ունեցի

### ISSUE THREAD

**Issue by hisusqristos** [hisusqristos/exercism-elm#3]
```elm
totalCards : List (Set Card) -> Int
totalCards collections =
    collections
        |> List.concatMap Set.toList
        |> removeDuplicates
        |> List.length

```

սա աշխատում ա, բայց տեսա ասումա `Set.union` ֊ով արվի

մտածում էի ոնց։ երևի ռեկուրսիվ, ու սենց էլ փորձում էի։ չհասցրի։

մի ժամ եմ տալիս սրան, եթե չլինի՝ փակում եմ իշյուն

**Comment by hisusqristos** [comment]
Լավ, մի լացեք

արեցի (խարտում է եղունգները) հեսա ցույց տամ

**Comment by hisusqristos** [comment]
> եթե չլինի՝ փակում եմ իշյուն

եղավ։ փակաաա

**Comment by antaranyan** [comment]
Կներեք իսկ լուծումները ռիվյուի ուղարկում եք?

**Comment by hisusqristos** [comment]
Հա
